# Generated by Django 5.1.7 on 2025-04-16 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_customer_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.EmailValidator(message='Введите корректный адрес электронной почты')]),
        ),
    ]
